### ISSUE TITLE
Adding headers to validate the API

### ISSUE THREAD

**Issue by ericaovo** [joanvila/raml-js-validator#14]
The API I'm working on requests an header, but I saw that the library doesn't support this feature at the moment. Cause of this, I'm not able to validate the API since I get back a 403.

E.g., in `curl` it would be:
```
curl -XPOST -v -H "Content-Type: application/json" **--header "keyHeader: valueHeader"** 'http://localhost:8080/myEndpoint' -d '{"foo": "bar"}' 
```

The changes would consist in adding a new method to parse the headers in `endpoint-builder.js` and to integrate it in `endpoint-checker.js`.

I've already made all the changes in a branch to support this functionality, happy to open a PR in case.

Any thoughts?

**Comment by joanvila** [comment]
Hi @ericaovo this is great!
Feel free to open the PR, just remember to add tests for the functionality 🙂

**Comment by joanvila** [comment]
It's published now! https://www.npmjs.com/package/raml-js-validator

**Comment by ericaovo** [comment]
Thanks a lot @joanvila !
